version: "3"

services:
  nginx:
    image: nginx:1.18-alpine
    tty: true
    volumes:
      - ./laravel:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    networks:
      - default

  app:
    build:
      context: .
    tty: true
    volumes:
      - ./laravel:/var/www
    expose:
      - 9000
    networks:
      - default

  db:
    image: mysql:5.7
    volumes:
      - mysql-db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    networks:
      - default

networks:
  default:
    driver: bridge

# VOLUMES
volumes:
  # MYSQL
  mysql-db:
    driver: local
  # REDIS
  redis-db:
    driver: local
