version: "3"

services:
  nginx:
    image: nginx:1.18-alpine
    tty: true
    ports:
      - "8000:80"
    networks:
      - default

  php-fpm:
    build:
      context: .
    tty: true
    volumes:
      - .:/var/www
    expose:
      - 9000
    networks:
      - default

networks:
  default:
    driver: bridge